name: healthy_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.8.1
  font_awesome_flutter: ^8.10.0
  charts_flutter: ^0.9.0
  pedometer: ^2.0.2
  percent_indicator: ^2.1.7+4
  table_calendar: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/step.png"

flutter:

  uses-material-design: true

  assets:
    - images/adim.png
    - images/kalp_atis.png